# Generated by Django 3.2.6 on 2021-08-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=70, null=True)),
                ('houseNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cherry.geolocation')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('transportation', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('environment', models.CharField(blank=True, max_length=50, null=True)),
                ('rooms', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('livingArea', models.IntegerField(blank=True, default=0, null=True)),
                ('plotArea', models.IntegerField(blank=True, default=0, null=True)),
                ('kindOfHouse', models.CharField(blank=True, max_length=50, null=True)),
                ('energyLabel', models.CharField(blank=True, max_length=50, null=True)),
                ('constructionYear', models.IntegerField(blank=True, default=0, null=True)),
                ('suitableFor', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ManyToManyField(blank=True, null=True, to='Cherry.ImageHome')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cherry.place')),
            ],
        ),
    ]
