# Generated by Django 3.2.6 on 2021-08-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cherry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagehome',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
